### ISSUE TITLE
I can't open the ipynb.

### ISSUE THREAD

**Issue by Syx2000** [ShowStopperTheSecond/L2_Siamese#1]
When i open the ipynb, it shows "Unreadable Notebook: D:\WorkSpace\Code\Jupyter Notebook\2022_Image_registration\L2_Siamese-main\l2siamese-samemodality.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "c...')"

I thought that your ipynb has some problems.

**Comment by robmarkcole** [comment]
@Syx2000 you can re-export from kaggle and there are no issues https://www.kaggle.com/code/javidtheimmortal/l2siamese-samemodality

**Comment by ShowStopperTheSecond** [comment]
Please check out [this](https://stackoverflow.com/questions/28908319/how-to-clear-jupyter-notebooks-output-in-all-cells-from-the-linux-terminal)
